# This program creates a star design within a circle using the ColabTurtle library
# -*- coding: utf-8 -*-
"""colab_turtle-turtle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10q0DCLc5sXeUYz1eX3sXIEK9ogrQGFkO
"""

!pip install ColabTurtle

#https://github.com/tolgaatam/ColabTurtle/blob/master/ColabTurtle/Turtle.py
from ColabTurtle.Turtle import *

initializeTurtle()
speed(10)
width(5)
bgcolor("white")
penup()
forward(150)
pendown()
color("black")

left(90)

for i in range(360):
    left(1)
    forward(1)

left(72)
forward(40)
right(72)
forward(40)

for i in range(5):

  left(90+54)
  forward(40)
  right(72)
  forward(40)

