# -*- coding: utf-8 -*-
"""Midterm-Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wKkhFcIm_1X9qOs896MUh9GbeK6Uc7kK
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

fig, ax = plt.subplots()

ax.plot()

rect = patches.Rectangle((0, 0), 4, 4,linewidth=1,edgecolor='r', fill=False   )
rect2 = patches.Rectangle((.75, .75), 2.5, 2.5,linewidth=1,edgecolor='b', fill=False  )

ax.add_patch(rect)
ax.add_patch(rect2)

plt.title("CS478 - Midterm - Ryan Michels")
plt.xlabel("x-axis")
plt.ylabel("y-axis")

plt.show()