# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fV0o43tI11B-l38k-fygp5K4vD459Xfw
"""

! python -m pip install requests

import requests

link = "https://old.nasdaq.com/screening/companies-by-industry.aspx?exchange=NASDAQ&render=download"
f = requests.get(link)
print(f.text)