# Using the given dataset, plot the GDP's of several countries against one another.
# -*- coding: utf-8 -*-
"""RMichels-Skill5-GDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RcsVJmTCqpb1mTl7KUzLZkqjEZ3XH2UW
"""

import matplotlib.pyplot as plt
import pandas as pd
import urllib.request
import math

url = "https://raw.githubusercontent.com/datasets/gdp/0be54c18d900edc37123f25b4eff014731c9e459/data/gdp.csv"  #grabs the csv file
datasets = pd.read_csv(url)                                                                                    #reads the csv file
datasets.set_index('Country Name', inplace=True)                                                                #indexes file by last name so that I can use loc to find a specific country name
dataset1 = datasets.loc['United States', ['Year', 'Value']]                                                   #I store both the GDP and Year associated with the specific country (US here)
dataset2 = datasets.loc['European Union', ['Year', 'Value']]
dataset3 = datasets.loc['China', ['Year', 'Value']]

plt.plot(dataset1['Year'].values, dataset1['Value'].values/10**9, label = "United States")                    #I plot the x value as the year, the y value as the 'Value' or GDP divided by 10^9 for smaller nums. 
plt.plot(dataset2['Year'].values, dataset2['Value'].values/10**9, 'g--', label = "EU")                        #the 'g--' specifies a dashed greeen line, and label specifies each line in the legend or key
plt.plot(dataset3['Year'].values, dataset3['Value'].values/10**9, 'or', label = "China")

plt.xlabel("Year")
plt.ylabel("GDP")
plt.title("Ryan Michels GDP Plot")
plt.legend()
plt.show()

#print(datasets.values)     #Very Important for the assignment

#plt.scatter()

#print(dataset1['Value'].values/10**10)